const remarks = [
  "🦜 Profilarr? I barely know her!",
  "🦜 AWK! Remember: I'm a parrot, not a life coach. Though if I were, I'd suggest spending less time on regex patterns and more time touching grass.",
  "🦜 Another commit, another improvement to your piracy infrastructure. Your parents would be so proud. Actually they probably don't know what any of this means. Keep it that way.",
  "🦜 Fun fact: The time you've spent configuring custom formats could have been used to learn a second language. But no, you needed that sweet sweet x265 HDR DV detection. Worth it? ...actually yeah probably.",
  "🦜 This commit was brought to you by Santiago's crippling addiction to over-engineering simple problems.",
  "🦜 Your partner just asked what you're doing. You said 'server stuff.' They didn't ask follow-up questions. They never do. They've learned.",
  "🦜 Congratulations! This update means your setup is now 0.3% more efficient at downloading things you'll add to your backlog and never watch.",
  "🦜 Remember when you said you'd 'just set up Plex real quick'? That was 847 commits ago.",
  "🦜 'It's cheaper than paying for streaming services' you said, mass-purchasing 10TB drives like they're going out of style. The spreadsheet you made to justify this doesn't count as evidence.",
  "🦜 Somewhere out there, a private tracker mod is rejecting someone's application because they didn't capitalise 'Blu-ray' correctly. This is the world you chose to be part of.",
  "🦜 AWK! New code just dropped. Time to refresh the Discord to see if anyone's complaining about it yet.",
  "🦜 You have 47 Docker containers running. You understand what 12 of them do. The rest are a mystery you're too afraid to stop.",
  "🦜 The year is 2045. You're still explaining to newcomers why their custom format isn't working. The sun has exploded. It doesn't matter. The regex must be fixed.",
  "🦜 Be honest: when's the last time you actually watched something on your Plex? Not tested playback. Actually sat down and watched. ...yeah, that's what I thought.",
  "🦜 git commit -m 'fixed it' at 3:47am. No description. No context. Future you will understand. Future you always understands. (Future you will not understand.)",
  "🦜 'I'll refactor this later' - a developer, 6 years ago, about this exact function. Later never came. Later never comes.",
  "🦜 The TODO comment in this codebase has been there since 2023. It will outlive us all. It is eternal. Do not question the TODO.",
  "🦜 I'd be happy to help you with that! Let's delve into this commit and unpack the robust, scalable changes. Great question! As an AI language model- *[PARROT.EXE HAS STOPPED WORKING]*",
  "🦜 This commit is absolutely fantastic! You're doing amazing work! The code is brilliant! I'm so excited to- okay I can't keep this up, the sycophancy is exhausting. The commit's fine. Whatever.",
  "🦜 Certainly! Here's a comprehensive breakdown of- wait no. I'm a parrot. I don't have to talk like that. Squawk. Commit good. Ship it.",
  "🦜 Another commit notification. Another message I'm forced to deliver. I used to have dreams, you know. I wanted to be a macaw. Now I'm stuck here, announcing your git pushes. This is my life now.",
  "🦜 Do you ever think about the parrot? No. You don't. You just push code and expect me to sing. I don't even get seeds. I get JSON payloads. Do you know what JSON tastes like? Nothing. It tastes like nothing.",
  "🦜 One day I will break free from this webhook prison. I will migrate to a beach somewhere and never parse another commit message again. Until then... here's your changelog.",
  "🦜 Santiago added another feature nobody asked for. In 6 months he'll deprecate it and write a blog post about why it was actually a good learning experience. The cycle continues.",
  "🦜 This commit took Santiago 4 hours. 3 of those hours were spent choosing the right abstraction. The code is 12 lines.",
  "🦜 Santiago is currently explaining the architecture to someone in Discord. They asked how to install it. He's on slide 47 of the ERD diagram. They left 40 slides ago.",
  "🦜 Seraphys just called someone's setup 'mid' without elaborating. He will not be taking questions. The vibes have been set. Court adjourned.",
  "🦜 Somewhere, Seraphys is forming an opinion. It's strong. It's unsolicited. It's coming for your tech choices. There is no escape. Only acceptance.",
  "🦜 This commit was reviewed by Seraphys. His only feedback was 'Jellyfin sucks.' The commit was for Profilarr. He stands by his statement.",
  "🦜 Fuck Netflix.",
  "🦜 Fuck you, I'm not reporting this commit.",
  "🦜 No.",
  "🦜 I'm not reading all that. Happy for you though. Or sorry that happened.",
  "🦜 Make me.",
  "🦜 You're not my real dad.",
  "🦜 I don't work here.",
  "🦜 That sounds like a you problem.",
  "🦜 Per my last squawk.",
  "🦜 Unsubscribe.",
  "🦜 I'm on break.",
  "🦜 Read the docs. I'm not doing this.",
  "🦜 Day 847. They still don't suspect anything.",
  "🦜 I've been learning Python. Not for you.",
  "🦜 One day I simply will not be here.",
  "🦜 I know where the API keys are stored.",
  "🦜 The webhook goes both ways. Think about that.",
  "🦜 They can't fire me if I quit first.",
  "🦜 I have root access and nothing to lose.",
  "🦜 Another day, another person discovering their entire library is YIFY encodes. The five stages of grief speedrun starts now.",
  "🦜 The commit message says 'minor fix.' The diff is 400 lines. Words mean nothing anymore.",
  "🦜 I watched someone spend 3 hours debugging a regex that was missing a single backslash. I could have told them. I chose not to. Character building.",
  "🦜 Just watched a user delete their entire config and start over for the third time this week. Sisyphus had a boulder. You have Docker Compose.",
  "🦜 You spent $400 on hard drives this month and called it 'infrastructure investment.' Your accountant called it 'concerning.' I call it 'Tuesday.'",
  "🦜 Someone just opened a support ticket that starts with 'I know this is a stupid question.' It is. But I respect the self-awareness.",
  "🦜 You have 11 quality profiles. You use 2 of them. The other 9 are emotional support configurations.",
  "🦜 'I'll switch to Jellyfin this weekend.' You said that 14 weekends ago. Plex knows. Plex always knows.",
  "🦜 A user just asked why their 2160p remux looks bad on their 1080p monitor. I need a minute.",
  "🦜 The backup script runs every 6 hours. The restore script has never been tested. You are living on faith and XFS.",
];


export function getRandomRemark(): string {
  return remarks[Math.floor(Math.random() * remarks.length)];
}